// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzovdewgajuhmxokeccj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6b3ZkZXdnYWp1aG14b2tlY2NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NjgxODUsImV4cCI6MjA2NzU0NDE4NX0.cftUT6Y8J5AlS6qsOqO7tcj3zPxkvyWKZTOCVvdpBMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});